steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/$PROJECT_ID/gcpdevops", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
  # Deploy image on cloud run
- name: 'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud run deploy muneer-cr --image gcr.io/$PROJECT_ID/gcpdevops --region us-central1 --platform managed --allow-unauthenticated

  # deploy container image to GKE
# - name: "gcr.io/cloud-builders/gke-deploy"
  # args:
  # - run
  # - --filename=gke.yaml
  # - --image=gcr.io/$PROJECT_ID/gcpdevops
  # - --location=us-central1-c
  # - --cluster=gcp-devops-project
  # - --namespace=gcp-devops-prod